export const data = [
  {
    id: 1,
    img: "phone1.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    userName: "Precious-ltd",
    name: `Apple Iphone X G4 GB Black `,
    price: `105,000`,
    cat: "mobile",
  },
  {
    id: 2,
    img: "phone3.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    userName: "Precious-ltd",
    name: `New Apple iPhone 12 Pro Max 128 GB White `,
    price: `540,000`,
    cat: "mobile",
  },
 
  {
    id: 3,
    img: "car.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Toyota Tacoma 4dr Double Cab 2016 White `,
    price: `18,500,000`,
    userName: "Fola alisson & co",
    cat: "car",
  },
 
  {
    id: 4,
    img: "car1.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Dodge Challenger R/T RWD 2017 White `,
    userName: "Richard-ltd",
    price: `15,499,999`,
    cat: "car",
  },
  {
    id: 5,
    img: "earpiece.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Samsung Galaxy S10+ Earpiece `,
    userName: "Trebdmax_ng",
    price: `5,000`,
    cat: "Accessories",
  },
  {
    id: 6,
    img: "earpiece1.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `iPhone Bluetooth Earpiece`,
    userName: "KenixBestGadgets concepts",
    price: `4,000`,
    cat: "Accessories",
  },

  {
    id: 7,
    img: "watch2.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `MICHEAL KORS Top Notch Smart Watch Available in Store`,
    userName: "Bizzcoture",
    price: `410,000`,
    cat: "watches",
  },
  {
    id: 8,
    img: "watch1.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Smartwatch Fullscreen 44mm Smart Watch With Powerbank`,
    userName: "Kc styles",
    price: `29,000`,
    cat: "watches",
  },
  {
    id: 8,
    img: "watch1.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Smartwatch Fullscreen 44mm Smart Watch With Powerbank`,
    userName: "Kc styles",
    price: `29,000`,
    cat: "watches",
  },
  {
    id: 8,
    img: "watch1.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Smartwatch Fullscreen 44mm Smart Watch With Powerbank`,
    userName: "Kc styles",
    price: `29,000`,
    cat: "watches",
  },
  {
    id: 8,
    img: "watch1.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Smartwatch Fullscreen 44mm Smart Watch With Powerbank`,
    userName: "Kc styles",
    price: `29,000`,
    cat: "watches",
  },
  {
    id: 8,
    img: "watch1.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Smartwatch Fullscreen 44mm Smart Watch With Powerbank`,
    userName: "Kc styles",
    price: `29,000`,
    cat: "watches",
  },
  {
    id: 8,
    img: "watch1.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Smartwatch Fullscreen 44mm Smart Watch With Powerbank`,
    userName: "Kc styles",
    price: `29,000`,
    cat: "watches",
  },
  {
    id: 8,
    img: "watch1.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Smartwatch Fullscreen 44mm Smart Watch With Powerbank`,
    userName: "Kc styles",
    price: `29,000`,
    cat: "watches",
  },
  {
    id: 9,
    img: "bed.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Classy 4.5ft Bedframe. `,
    userName: "Eagle grace Continental",
    price: `95,000`,
    cat: "furniture",
  },
  {
    id: 10,
    img: "bed1.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Complete Bed With Bed Drawer and Dresser `,
    userName: "Royal Heroes Furniture",
    price: `95,000`,
    cat: "furniture",
  },
  {
    id: 11,
    img: "earpiece.png",
    img1: "earpiece.png",
    img2: "earpiece.png",
    img3: "earpiece.png",
    img4: "earpiece.png",
    img5: "earpiece.png",
    name: `Complete Bed With Bed Drawer and Dresser `,
    userName: "Royal Heroes Furniture",
    price: `2,000`,
    cat: "furniture",
  },

];
